### ISSUE TITLE
windows script

### ISSUE THREAD

**Issue by thomisus** [plambe/zabbix-nvidia-smi-multi-gpu#1]
Hi, thank you for your work.
Could you make a windows script for GPUS discovery? I tried using awk but awk for windows doesn't work very well with quotes.

**Comment by plambe** [comment]
Hi,
I've created a Windows batch script that attempts to do that. It's in commit https://github.com/plambe/zabbix-nvidia-smi-multi-gpu/commit/7f116de1bb6f8e61fd0dbdd758e88390f28ed404 - already on the master branch.

I don't have a Windows machine with multiple nvidia gpus so I am unable to properly test it at the moment.

**Comment by thomisus** [comment]
Hi, i tested the script on windows with multiple GPUs and it works as intended. Thank you very much ;)

**Comment by plambe** [comment]
Issue confirmed to be solved. Closing.
