### ISSUE TITLE
Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 44 | Column: 91]

### ISSUE THREAD

**Issue by maxrodkin** [plambe/zabbix-nvidia-smi-multi-gpu#10]
hello, 
got error while importing zbx_nvidia-smi-multi-gpu.xml
Import failed
Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 44 | Column: 91]
zabbix is latest

**Comment by plambe** [comment]
Hi,

My first result when searching for "Specification mandates value for attribute data-pjax-transient" in duckduckgo is: https://github.com/adubkov/zbx_nginx_template/issues/4
The second answered issue I found has the same solution: https://github.com/cavaliercoder/libzbxpgsql/issues/81

Have you tried this?

**Comment by maxrodkin** [comment]
> Have you tried this?
hello plambe, thank u for answer.
i dad using https://github.com/RichardKav/zabbix-nvidia-smi-integration
 , successfully
