### ISSUE TITLE
get_gplus_info.sh no found

### ISSUE THREAD

**Issue by sevketozturk** [plambe/zabbix-nvidia-smi-multi-gpu#12]
Hi,
I need help to understand and fix.

I follow and install the script in /etc/zabbix/scripts/ and add /etc/zabbix/zabbix_agentd.d/userparameter_nvidia-smi.conf

I also import the template and assign that template to the server. I try to run the command manually to make sure I don't miss something.

 
![image](https://user-images.githubusercontent.com/45919074/108374910-8322b600-7212-11eb-873e-21caad34b690.png)

![image](https://user-images.githubusercontent.com/45919074/108375419-fcbaa400-7212-11eb-805d-53eaf257228a.png)

![image](https://user-images.githubusercontent.com/45919074/108376260-dd704680-7213-11eb-9926-737230d69afd.png)

can you help me,thnks.

**Comment by RichardKav** [comment]
When you run the script sudo get_gpu_info.sh your current working directory is:

**/etc/zabbix/script/**

but the agent seems to be pointing to:

**/etc/zabbix/scripts/**  

so the difference is the "s" that is causing issues.

**Comment by sevketozturk** [comment]
see another, look another.  the problem is solved. thank you sir . 👍
