### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by olifre** [plambe/zabbix-nvidia-smi-multi-gpu#14]
Hi, 

many thanks for this useful plugin! 
Could you please add a `LICENSE` to your project to allow contributions and "safe" usage of it? 

Thanks! :smile:

**Comment by plambe** [comment]
I had no idea that could be an issue. 

Does it have to be really written in legalese, like MIT, BSD, GPL, CC-whatever?

**Comment by RichardKav** [comment]
I've had people enquire before particularly from large businesses that require licences for any software they use. Otherwise although its online and available there isn't strictly any rights given allowing the use of the software.

**Comment by plambe** [comment]
Added an MIT license with an addition from me at the top (your repo, @RichardKav, is mentioned). I think it should be OK now.

**Comment by RichardKav** [comment]
MIT is open and permissive so it should serve his needs. 

I've always been glad to see how far you took the early work I did with Zabbix and Nvidia. Its quite an advance on the little bit I did.

**Comment by olifre** [comment]
> I had no idea that could be an issue.

If you do not specify any license, this usally means "all rights reserved". In other words, it would mean that if I contribute, you could decide afterwards to take the project offline and sell the code. 
If a nit-picky legal guy gets serious, it might even mean that I am not allowed to even fork your project to contribute to it — since I would "distribute" your code (in my fork). While GitHub tends to be a place with enthusiastic Open Source developers, sometimes such nasty things pop up. 

Specifying a copyleft license protect contributors (and you) from all of this ;-). 

It also contains a paragraph stating you are not liable if your code is used and does anything unexpected (like destroying a GPU). Will unlikely, there are probably some countries in which it might be possible to sue a developer if this is not explicitly stated. 

> Does it have to be really written in legalese, like MIT, BSD, GPL, CC-whatever?

I personally would be fine with any of the "usual" OSI licenses (see e.g. https://opensource.org/licenses ). If you place a `LICENSE` file in the repository with content matching one of these licenses, GitHub will even realize and mark your repo as using this license. 

Some examples (from my repos) are:
* https://github.com/olifre/userstyles
  This uses the `Unlicense`. I used that one there since it mostly is a backup of a configuration I use (which may be helpful to others), and I would not care if anybody steals / sells it (it's too trivial to be of actual use). 
* https://github.com/olifre/dockerhub2oci/blob/master/LICENSE
  here I use an `Apache 2.0` license. This also allows others to take the code and include it in their project, even if it is licensed under another license, since I considered this a useful tool for integration into other tools. 
* https://github.com/olifre/latex-graphics/blob/master/LICENSE
  Here I use `GPL-3`. That's one of the licenses enforcing `copyleft` so forked code also has to be GPL-3. 

While I was typing, you already added MIT. I'm perfectly fine with that. 
For reference, I am academic and we'd like to use parts of this in our configuration management to monitor GPU nodes, so I would modify your code (to put snippets of it into `Puppet`). MIT allows me to do so.

**Comment by plambe** [comment]
@RichardKav, I wouldn't have even started if I hadn't found your work. 

@olifre, I'm very glad this is useful, especially outside of the niche I wrote it for - mining on gpus on home-grade hardware, with bad pcie cables, etc. That's the second time some small piece of code I wrote will be used in academia to my knowledge. Cool.

**Comment by olifre** [comment]
> I'm very glad this is useful

It sure is! :+1: 
And also thanks to @RichardKav for starting this :-).
