### ISSUE TITLE
Perl one-liner instead of get_gpus_info.sh

### ISSUE THREAD

**Issue by naoh16** [plambe/zabbix-nvidia-smi-multi-gpu#2]
Hi, this is great work, and I hope we can use this easier.
In my environment, I can replace the `get_gpus_info.sh` script into the one-liners with perl as following:

````
nvidia-smi -L | perl -le 'while(<>){push @a,qq|{"{#GPUINDEX}":"$1", "{#GPUUUID}":"$2"}| if(/GPU (
\d+).*UUID\: (.*)\)$/);} print qq|{"data":[\n| . join(",\n", @a) . qq|\n]}|;'
````

So, we can replace the UserParameter:

````
UserParameter=gpu.discovery,nvidia-smi -L | perl -le 'while(<>){push @a,qq|{"{#GPUINDEX}":"$1", "{#GPUUUID}":"$2"}| if(/GPU (
\d+).*UUID\: (.*)\)$/);} print qq|{"data":[\n| . join(",\n", @a) . qq|\n]}|;'
````

Note that, we need setting of PATH environment for `nvidia-smi` and `perl` commands.

**Comment by plambe** [comment]
Hi,

My first thought is that I don't want any more dependencies, such as perl, however, I'll think about adding this to the main branch, or at least as an alternative in the readme file. 

Thanks for sharing!

**Comment by naoh16** [comment]
Hi,

I agree to your reply. I think my script should not be added main branch.
It's too much for me to your consideration.

Thanks.
