### ISSUE TITLE
Script Bash

### ISSUE THREAD

**Issue by Abolah** [plambe/zabbix-nvidia-smi-multi-gpu#4]
Heyo,

I am having issue with the bash script you provide.
It  says  `get_gpus_info.sh: 23: get_gpus_info.sh: Syntax error: redirection unexpected`

Can you help me fix it ?

**Comment by plambe** [comment]
Hi,

It seems you are using a different version of bash, or bash with different settings. 

Can you give me more details about what distribution you are using and what customizations you have done, so that I can attempt to simulate the same conditions?

**Comment by Abolah** [comment]
The script is running on an ubuntu 16.04.4 LTS
There is not much customization. I have 4 GTX1080 in it

**Comment by plambe** [comment]
Did you fix your issue? If you did, please feel free to share how.

**Comment by zaheerabbas1988** [comment]
You are likely to face this issue on Ubunut.
So instead of `sudo sh ./get_gpus_info.sh` use `sudo bash ./get_gpus_info.sh`
