### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by Ro1han** [plambe/zabbix-nvidia-smi-multi-gpu#6]
below is my output from server:
![image](https://user-images.githubusercontent.com/10594821/44613710-73e16e00-a84a-11e8-8f3c-72d0439d7035.png)

in the zabbix UI, where shows "Value should be a JSON object."

**Comment by plambe** [comment]
Please elaborate. Here's a screenshot from a machine, on which this template works as expected: 

![image](https://user-images.githubusercontent.com/5834002/44615537-f49d6b80-a844-11e8-9105-18f546fe837d.png)

**Comment by Ro1han** [comment]
Hi issue was caused by sudo permission, get_gpus_info.sh scripts should be put in sudoers file

**Comment by Ro1han** [comment]
I fixed issue in centos, but ubuntu it's still having issue
![image](https://user-images.githubusercontent.com/10594821/44654310-d04bb580-aa23-11e8-9406-ede48a92e065.png)

**Comment by plambe** [comment]
Hi,

Can you put your zabbix client in debug mode? Add (or edit it if you already have it) the following line in your zabbix agent configuration file:

```
DebugLevel=4
```

After you do that, check your log for a line like:

```
   852:20180901:094521.647 EXECUTE_STR() command:'/home/miner/XXXXXXXXXXXX/get_gpus_info.sh' len:325 cmd_result:'{
```

What I want to see to be able to help you, when everything works, looks like: 

```
   852:20180901:094521.647 EXECUTE_STR() command:'/home/miner/XXXXXXXXXXXX/get_gpus_info.sh' len:325 cmd_result:'{
"data":[
{"{#GPUIN'
   852:20180901:094521.647 Sending back [{
"data":[
{"{#GPUINDEX}":"0", "{#GPUUUID}":"GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"},
{"{#GPUINDEX}":"1", "{#GPUUUID}":"GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"},
{"{#GPUINDEX}":"2", "{#GPUUUID}":"GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"},
{"{#GPUINDEX}":"3", "{#GPUUUID}":"GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}
]
}]
```

So I want to know what would be different with your setup in this output. 

I used a command like the following to see what I copied above without too much spam:

```
tail -10000 /var/run/zabbix/zabbix_agentd.log | grep -i gpu.discovery -A 20 -B 10
```

**Comment by plambe** [comment]
One more thing, you said:
> I fixed issue in centos [..]

I'm curious, what was the issue and what was the fix?

**Comment by plambe** [comment]
Closing this due to lack of any feedback
